version: '2'

services:
  mongodb:
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/mongo/Dockerfile
    volumes:
      - progdash-mongo-data:/data/db
      - progdash-mongo-config:/data/configdb
    ports:
      - 27017:27017

  mongoadmin:
    ports:
      - 8081:8081

  java:
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/java/Dockerfile
    ports:
      - 8080:8080

volumes:
  progdash-mongo-data:
    driver: local
  progdash-mongo-config:
    driver: local