version: '2'

services:
  mongodb:
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/mongo/Dockerfile
    volumes:
      - progdash-mongo-data:/data/db
      - progdash-mongo-config:/data/configdb
    ports:
      - 27017:27017

  mongoadmin:
    ports:
      - 8081:8081

  java:
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/java/Dockerfile
    volumes:
        - C:/dev/log/progdash:/opt/progdash/logs
    ports:
      - 8080:8080

  nginx:
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/nginx/Dockerfile
    ports:
      - 8090:80

  cronjobs:
    build:
      context: ./
      dockerfile: ./docker/dockerfiles/cronjobs/Dockerfile
    volumes:
      - progdash-mongo-backup:/data/backups

volumes:
  progdash-mongo-data:
    driver: local
  progdash-mongo-config:
    driver: local
  progdash-mongo-backup:
    driver: local