version: '2'

services:
  mongodb:
    build:
      context: ./
      dockerfile: ./build/dockerfiles/mongo/Dockerfile
    volumes:
      - progdash-mongo-data:/data/db
      - progdash-mongo-config:/data/configdb
    ports:
      - 27017:27017

  mongoadmin:
    ports:
      - 8081:8081

  node:
    container_name: progdash-dev-node
    build:
      context: .
      dockerfile: ./build/dockerfiles/dev/node/Dockerfile
    command: ng serve --host 0.0.0.0 --configuration hmr
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - 4200:4200

volumes:
  progdash-mongo-data:
    driver: local
  progdash-mongo-config:
    driver: local