version: '2'

services:
  mongodb:
    image: rancher-registry.woonoz.com:5000/woonoz/progdash-mongo:${DOCKER_TAG}
    container_name: progdash-mongo
    user: mongodb
    environment: &mongo_env
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASS}
      MONGO_PROGDASH_DB: ${MONGO_PROGDASH_DB}
      MONGO_PROGDASH_USER: ${MONGO_PROGDASH_USER}
      MONGO_PROGDASH_PASS: ${MONGO_PROGDASH_PASS}

  mongoadmin:
    image: mongo-express
    container_name: progdash-mongo-admin
    depends_on:
      - mongodb
    links:
      - mongodb:mongo
    environment:
      TZ: Europe/Paris
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASS}

  java:
    image: rancher-registry.woonoz.com:5000/woonoz/progdash-java:${DOCKER_TAG}
    container_name: progdash-java
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_PROGDASH_DB: ${MONGO_PROGDASH_DB}
      MONGO_PROGDASH_USER: ${MONGO_PROGDASH_USER}
      MONGO_PROGDASH_PASS: ${MONGO_PROGDASH_PASS}
      LOG_GENERAL_LEVEL: ${LOG_GENERAL_LEVEL}
      SPRING_PROFILES: ${SPRING_PROFILES}
    command: >
      /bin/bash -c "envsubst < /opt/progdash/application.properties.template > /opt/progdash/application.properties
      && rm /opt/progdash/application.properties.template && /usr/bin/java -jar /opt/progdash/webservices.jar --spring.config.location=/opt/progdash/application.properties"
    depends_on:
      - mongodb
    links:
      - mongodb:mongo

  nginx:
    image: rancher-registry.woonoz.com:5000/woonoz/progdash-nginx:${DOCKER_TAG}
    container_name: progdash-nginx
    depends_on:
      - java

  cronjobs:
    image: rancher-registry.woonoz.com:5000/woonoz/progdash-cronjobs:${DOCKER_TAG}
    container_name: progdash-cronjobs
    environment:
      <<: *mongo_env
      LOCAL_USER_ID: ${LOCAL_USER_ID}
    depends_on:
      - mongodb
    links:
      - mongodb:mongo